version: '2'
services:
  default:
    container_name: default
    image: docker-registry.ai-traders.com/mono-ide:1.4.0
    links:
      - liget:liget
    volumes:
      - ${IDE_IDENTITY}:/ide/identity:ro
      - ${IDE_WORK}:/ide/work
    env_file:
      - ${ENV_FILE}
  liget:
    image: microsoft/dotnet:2.0.0-runtime-jessie
    command: dotnet /app/LiGet.App.dll
    volumes:
      - ${IDE_WORK}/src/LiGet.App/bin/Release/netcoreapp2.0/publish:/app:ro
      - ${IDE_WORK}/e2e/input:/e2e-input:ro
      - ${IDE_WORK}/e2e/debug.log4net.xml:/etc/liget/log4net.xml:ro
    env_file:
      - ${ENV_FILE}
