pipelines:
  liget:
    group: stcdev
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
    stages:
      - build:
          clean_workspace: true
          jobs:
            build:
              elastic_profile_id: w.c2.m2048.e10
              artifacts:
                - build:
                    source: src/LiGet.App/bin/Release/netcoreapp2.0/publish/**/*
                    destination: src/LiGet.App/bin/Release/netcoreapp2.0/publish
                - build:
                    source: tests/LiGet.Tests/bin/Release/netcoreapp2.0/publish/**/*
                    destination: tests/LiGet.Tests/bin/Release/netcoreapp2.0/publish
              tasks:
               - exec:
                  command: ide
                  arguments:
                    - "./tasks.sh build"
      - test_pack:
          clean_workspace: true
          jobs:
            docker:
              resources:
                - docker_builder
              artifacts:
                - build:
                    source: docker/imagerc*
                    destination:
              tasks:
               - fetch:
                  stage: build
                  job: build
                  source: src/LiGet.App/bin/Release/netcoreapp2.0/publish
                  destination: docker
               - exec:
                  command: /bin/bash
                  arguments:
                    - -c
                    - "ops_docker_push=true ./tasks.sh build_docker ${GO_PIPELINE_LABEL}"
            unit:
              elastic_profile_id: w.c2.m2048.e10
              tasks:
               - fetch:
                  stage: build
                  job: build
                  source: tests
                  destination:
               - exec:
                  command: ide
                  arguments:
                    - "./tasks.sh test"
      - e2e:
          clean_workspace: true
          jobs:
            functional:
              elastic_profile_id: w.c2.m2048.e10
              tasks:
               - fetch:
                  stage: test_pack
                  job: docker
                  source: imagerc
                  destination: docker/
                  is_file: true
               - exec:
                  command: /bin/bash
                  arguments:
                    - -c
                    - "./tasks.sh test_docker"
               - exec:
                  run_if: failed
                  command: /bin/bash
                  arguments:
                    - -c
                    - dmesg | tail -n 100
            stress:
              elastic_profile_id: w.c2.m4096.e200
              timeout: 60
              environment_variables:
                LIGET_LIBUV_THREAD_COUNT: 16
              tasks:
               - fetch:
                  stage: test_pack
                  job: docker
                  source: imagerc
                  destination: docker/
                  is_file: true
               - exec:
                  command: /bin/bash
                  arguments:
                    - -c
                    - "./tasks.sh stress_docker"
               - exec:
                  run_if: failed
                  command: /bin/bash
                  arguments:
                    - -c
                    - dmesg | tail -n 100
      - release:
          clean_workspace: true
          jobs:
            code:
              elastic_profile_id: w.c2.m2048.e10
              tasks:
               - exec:
                  command: /bin/bash
                  arguments:
                    - -c
                    - "./tasks.sh code_release"
      - publish:
          clean_workspace: true
          jobs:
            docker_private:
              resources:
                - docker_builder
              tasks:
                - fetch:
                    stage: test_pack
                    job: docker
                    source: imagerc
                    destination: docker/
                    is_file: true
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks.sh publish_docker_private
            docker_public:
              resources:
                - docker_builder
              secure_variables:
                DOCKERHUB_PASSWORD: CioRNFm+WifCZPcqU+78+A==
              tasks:
                - fetch:
                    stage: test_pack
                    job: docker
                    source: imagerc
                    destination: docker/
                    is_file: true
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks.sh publish_docker_public
      - github_release:
          clean_workspace: true
          jobs:
            github:
              elastic_profile_id: w.c2.m2048.e10
              secure_variables:
                GITHUB_TOKEN: J2VpEh3xtuzZuU+kaHVCLM/glpKCSXKhGt3XCmZZTOLARPVLXFPKUaKiqeQ5smiT
              tasks:
                - fetch:
                    stage: build
                    job: build
                    source: src/LiGet.App/bin/Release/netcoreapp2.0/publish
                    destination:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks.sh github_release
